version: "3.7"
services:

  #Laravel App
  app:
    build:
      context: ./docker/php/${DOCKER_PHP_VERSION:-8.2}
      dockerfile: Dockerfile
      args:
        xdebug_enabled: ${DOCKER_PHP_XDEBUG_ENABLED:-off}
        DOCKER_USER: '${DOCKER_USER:-laravel}'
        DOCKER_UID: '${DOCKER_PUID:-1000}'
    image: ${COMPOSE_PROJECT_NAME}-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    environment:
        XDEBUG_MODE: '${DOCKER_PHP_XDEBUG_MODE:-off}'
    volumes:
      - ./:/var/www/html
      - ./docker/php/${DOCKER_PHP_VERSION}/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app_network
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - '${DOCKER_NGINX_PORT:-80}:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/dev/:/etc/nginx/conf.d/
    links:
      - app
      - postgres
    networks:
      - app_network
    depends_on:
      - app
      - postgres

  # Database
  postgres:
    image: postgres:latest
    volumes:
      - apppgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: '${DB_DATABASE:-laravel}'
      POSTGRES_USER: '${DB_USERNAME:-laravel}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-abc123}'
    ports:
      - "${DOCKER_POSTGRES_PORT:-5432}:5432"
    networks:
      - app_network

  # Redis Database
  redis:
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    image: redis
    restart: unless-stopped
    volumes:
      - 'appredis:/data'
    environment:
      - PUID=${DOCKER_PUID:-1000}
      - PGID=${DOCKER_PGID:-1000}
      - TZ=${DOCKER_TZ:-Australia/Brisbane}
    ports:
      - ${DOCKER_REDIS_PORT:-6379}:6379
    networks:
      - app_network

volumes:
  appredis:
    driver: local
  apppgsql:
    driver: local

networks:
  app_network:
    driver: bridge
